### ISSUE TITLE
Zip Gruntfile.js

### ISSUE THREAD

**Issue by jorgecasar** [mikermcneil/sails-deploy-azure#10]
I don't understand why zip `task` folder and doesn't zip `Gruntfile.js`. Is the folder useful without the file?

https://github.com/mikermcneil/sails-deploy-azure/blob/master/index.js#L323

**Comment by felixrieseberg** [comment]
The folder is indeed useful - it's still used internally by Sails, but we want to discourage usage of Grunt up in Azure, therefore the missing Gruntfile.

On that note: I just updated the readme with way better instructions, so I hope the whole thing makes a bit more sense now :) I'll be closing this in the meantime.

**Comment by jorgecasar** [comment]
Thanks so much, very useful. I will try again.
