### ISSUE TITLE
Does this project work?

### ISSUE THREAD

**Issue by chandlerkent** [mikermcneil/sails-deploy-azure#13]
I've been trying to integrate this into my sails project, but cannot get this to work. I think I've followed everything in the README, but `sails deploy` doesn't do anything (I just get the help output like it doesn't recognize the deploy command).

Any tips?

**Comment by felixrieseberg** [comment]
Hey @chandlerkent, did you use the commit numbers provided in the readme? It's been a while since Sails officially released, meaning that the version you install with `npm install sails` doesn't work unless you specify the exact commit that contains the required features...

**Comment by chandlerkent** [comment]
@felixrieseberg thanks for the response.

That was exactly what I missed.

Out of curiosity, which branch is this commit in? Looking at the HEAD of master, I don't see any changes to this file that would make running `sails deploy` function:

https://github.com/balderdashy/sails/blob/master/bin/sails.js

Am I looking in the wrong place or misunderstanding how this works?

**Comment by felixrieseberg** [comment]
There's nothing super specific about the commit I picked - it just happened to be the latest this whole thing worked with. It's super duper possible that it still works with the latest version (`balderdashy/sails`).

The code that catches all `deploy` stuff is here: https://github.com/balderdashy/sails/blob/master/bin/sails.js#L79-L85

**Comment by chandlerkent** [comment]
Completely missed that. Thanks!
