### ISSUE TITLE
Could somebody with npm rights please publish?

### ISSUE THREAD

**Issue by felixrieseberg** [mikermcneil/sails-deploy-azure#8]
Thanks much :+1:

**Comment by sgress454** [comment]
Done!

**Comment by sedouard** [comment]
@sgress454 are you sure you published? 
![screen shot 2015-04-13 at 12 58 21 pm](https://cloud.githubusercontent.com/assets/3053263/7124310/c8d1cc26-e1dc-11e4-8c15-c13ded3dd2ed.png)

**Comment by sgress454** [comment]
Oh--I think what I did was add Felix as an owner to the NPM package.

**Comment by sgress454** [comment]
Just pushed out v0.2.7 just in case.

**Comment by sedouard** [comment]
thanks!
